# Uncomment the next line to define a global platform for your project
#platform :ios, '12.0'

target 'iLinX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iLinX
    
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'CocoaAsyncSocket'
    pod 'SDWebImage', '~> 4.0'
    pod 'Queuer'
end
